services:
  # Servicio Backend LOCAL con hot-reloading
  backend:
    build:
      context: ./backend  # Ruta a la carpeta con tu Dockerfile
      dockerfile: Dockerfile
    container_name: taskpro-backend-local
    ports:
      - "8000:8000"
    volumes:
      # Monta tu código local para que el hot-reloading funcione
      - ./backend/app:/app
      # Montar la llave de Google Cloud (asumiendo que está en ./config)
      - ./config/primeval-falcon-474622-h1-d5121477addc.json:/app/config/gcloud-key.json:ro
      # Montar el archivo .env
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      # Las variables principales vienen del .env, estas son solo para override si es necesario
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/gcloud-key.json
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload